# Generated by Django 4.2.9 on 2024-01-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backEnd", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToDoList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=255)),
            ],
        ),
    ]
