# Generated by Django 4.2.9 on 2024-01-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backEnd", "0002_todolist"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(default="")),
            ],
        ),
    ]
