# Generated by Django 4.2.9 on 2024-01-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backEnd", "0004_list_delete_todolist_item_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(default="", unique=True),
        ),
    ]
