# Generated by Django 4.2.9 on 2024-01-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backEnd", "0006_alter_item_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(default=""),
        ),
    ]
