# Generated by Django 4.2.9 on 2024-01-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backEnd", "0007_alter_item_text"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="item",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(default="", unique=True),
        ),
    ]
